version: '3.3'

services:
  db:
    image: mariadb:latest
    container_name: ccsdk-mariadb
    ports:
    - "3306:3306"
    volumes:
    - ~/vm_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdnctl
      MYSQL_DATABASE: sdnctl
      MYSQL_USER: sdnctl
      MYSQL_PASSWORD: sdnctl
  blueprints-processor:
    depends_on:
    - db
    image: onap/ccsdk-blueprintsprocessor:latest
    container_name: bp-rest
    ports:
    - "8000:8080"
    restart: always
    volumes:
    - ~/share/vm_ms/blueprintsprocessor/config:/opt/app/onap/config
    - ~/share/vm_ms/blueprintsprocessor/logs:/logs
    environment:
      APPLICATIONNAME: BlueprintsProcessor
      BUNDLEVERSION: 1.0.0
      APP_CONFIG_HOME: /opt/app/onap/config
      STICKYSELECTORKEY:
      ENVCONTEXT: dev