version: '3.3'

services:
  db:
    image: mariadb:latest
    container_name: ccsdk-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ~/vm_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdnctl
      MYSQL_DATABASE: sdnctl
      MYSQL_USER: sdnctl
      MYSQL_PASSWORD: sdnctl
  cds-controller-default:
    depends_on:
      - db
    image: onap/ccsdk-blueprintsprocessor:latest
    container_name: cds-controller-default
    hostname: cds-controller-default
    ports:
      - "8000:8080"
      - "9111:9111"
    restart: always
    volumes:
      - blueprints-deploy:/opt/app/onap/blueprints/deploy
    environment:
      APPLICATIONNAME: cds-controller
      BUNDLEVERSION: 1.0.0
      APP_CONFIG_HOME: /opt/app/onap/config
      STICKYSELECTORKEY:
      ENVCONTEXT: dev
  command-executor:
    depends_on:
      - db
    image: onap/ccsdk-commandexecutor:latest
    container_name: bp-command-executor
    ports:
      - "50051:50051"
    restart: always
    volumes:
      - blueprints-deploy:/opt/app/onap/blueprints/deploy
  py-executor-default:
    depends_on:
      - db
    image: onap/ccsdk-py-executor
    container_name: py-executor-default
    hostname: py-executor-default
    ports:
      - "50052:50052"
    restart: always
    volumes:
      - blueprints-deploy:/opt/app/onap/blueprints/deploy
    environment:
      APPLICATIONNAME: py-executor
      BUNDLEVERSION: 1.0.0
      APP_CONFIG_HOME: /opt/app/onap/config
      STICKYSELECTORKEY:
      ENVCONTEXT: dev
      APP_PORT: 50052
      AUTH_TYPE: tls-auth
      LOG_FILE: /opt/app/onap/logs/application.log

volumes:
  blueprints-deploy:
