version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: ccsdk-mariadb
    networks:
      - cds-network
    ports:
      - "3306:3306"
    volumes:
      - target: /var/lib/mysql
        type: volume
        source: mysql-data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdnctl
      MYSQL_DATABASE: sdnctl
      MYSQL_USER: sdnctl
      MYSQL_PASSWORD: sdnctl
  nats:
    image: nats-streaming:latest
    container_name: nats
    hostname: nats
    command: "-cid cds-cluster --auth tokenAuth -store file -dir /opt/app/onap/nats/store --cluster_node_id nats-0"
    networks:
      - cds-network
    ports:
      - "8222:8222"
      - "4222:4222"
    restart: always
    volumes:
      - target: /opt/app/onap/nats/store
        type: volume
        source: nats-store
  cds-controller-0:
    depends_on:
      - db
      - nats
    image: onap/ccsdk-blueprintsprocessor:latest
    container_name: cds-controller-0
    hostname: cds-controller-0
    networks:
      - cds-network
    ports:
      - "8000:8080"
      - "9111:9111"
    restart: always
    volumes:
      - target: /opt/app/onap/blueprints/deploy
        type: volume
        source: blueprints-deploy
      - target: /opt/app/onap/config
        type: volume
        source: controller-config
    environment:
      # Same as hostname and container name
      CLUSTER_ENABLED: "true"
      CLUSTER_ID: cds-cluster
      CLUSTER_NODE_ID: cds-controller-0
      CLUSTER_MEMBERS: cds-controller-0,resource-resolution-0
      CLUSTER_STORAGE_PATH: /opt/app/onap/config/cluster
      #CLUSTER_CONFIG_FILE: /opt/app/onap/config/atomix/atomix-multicast.conf
      NATS_CLUSTER_ID: cds-cluster
      APP_NAME: cds-controller
      BUNDLEVERSION: 1.0.0
      APP_CONFIG_HOME: /opt/app/onap/config
      STICKYSELECTORKEY:
      ENVCONTEXT: dev
  resource-resolution-0:
    depends_on:
      - db
      - nats
    image: onap/ccsdk-blueprintsprocessor:latest
    container_name: resource-resolution-0
    hostname: resource-resolution-0
    networks:
      - cds-network
    ports:
      - "8001:8080"
      - "9112:9111"
    restart: always
    volumes:
      - target: /opt/app/onap/blueprints/deploy
        type: volume
        source: blueprints-deploy
      - target: /opt/app/onap/config
        type: volume
        source: resource-resolution-config
    environment:
      CLUSTER_ENABLED: "true"
      CLUSTER_ID: cds-cluster
      CLUSTER_NODE_ID: resource-resolution-0
      CLUSTER_MEMBERS: cds-controller-0,resource-resolution-0
      CLUSTER_STORAGE_PATH: /opt/app/onap/config/cluster
      #CLUSTER_CONFIG_FILE: /opt/app/onap/config/atomix/atomix-multicast.conf
      NATS_CLUSTER_ID: cds-cluster
      APP_NAME: resource-resolution
      BUNDLEVERSION: 1.0.0
      APP_CONFIG_HOME: /opt/app/onap/config
      STICKYSELECTORKEY:
      ENVCONTEXT: dev
  py-executor-0:
    depends_on:
      - db
      - nats
    image: onap/ccsdk-py-executor
    container_name: py-executor-0
    hostname: py-executor-0
    networks:
      - cds-network
    ports:
      - "50052:50052"
    restart: always
    volumes:
      - target: /opt/app/onap/blueprints/deploy
        type: volume
        source: blueprints-deploy
    environment:
      CLUSTER_ID: cds-cluster
      CLUSTER_NODE_ID: py-executor-0
      CLUSTER_MEMBERS: cds-controller-0,resource-resolution-0,py-executor-0
      NATS_CLUSTER_ID: cds-cluster
      APP_NAME: py-executor
      BUNDLEVERSION: 1.0.0
      APP_CONFIG_HOME: /opt/app/onap/config
      STICKYSELECTORKEY:
      ENVCONTEXT: dev
      APP_PORT: 50052
      AUTH_TYPE: tls-auth
      LOG_FILE: /opt/app/onap/logs/application.log
volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/mysql/data
      o: bind
  nats-store:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/nats/nats-0/store
      o: bind
  blueprints-deploy:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/blueprints/deploy
      o: bind
  controller-config:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/cds-controller/cds-controller-0/config
      o: bind
  resource-resolution-config:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/resource-resolution/resource-resolution-0/config
      o: bind

networks:
  cds-network:
    driver: bridge
