version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: ccsdk-mariadb
    networks:
      - cds-network
    ports:
      - "3306:3306"
    volumes:
      - target: /var/lib/mysql
        type: volume
        source: mysql-data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdnctl
      MYSQL_DATABASE: sdnctl
      MYSQL_USER: sdnctl
      MYSQL_PASSWORD: sdnctl
  nats:
    image: nats-streaming:latest
    container_name: nats
    hostname: nats
    command: "-cid cds-cluster --auth tokenAuth -store file -dir /opt/app/onap/nats/store --cluster_node_id nats"
    networks:
      - cds-network
    ports:
      - "8222:8222"
      - "4222:4222"
    restart: always
    volumes:
      - target: /opt/app/onap/nats/store
        type: volume
        source: nats-store
  cds-controller-default:
    depends_on:
      - db
      - nats
    image: onap/ccsdk-blueprintsprocessor:latest
    container_name: cds-controller-default
    hostname: cds-controller-default
    networks:
      - cds-network
    ports:
      - "8000:8080"
      - "9111:9111"
    restart: always
    volumes:
      - target: /opt/app/onap/blueprints/deploy
        type: volume
        source: blueprints-deploy
      - target: /opt/app/onap/config
        type: volume
        source: controller-config
    environment:
      APP_NAME: cds-controller
      BUNDLEVERSION: 1.0.0
      APP_CONFIG_HOME: /opt/app/onap/config
      STICKYSELECTORKEY:
      ENVCONTEXT: dev
  command-executor:
    depends_on:
      - db
    image: onap/ccsdk-commandexecutor:latest
    container_name: bp-command-executor
    networks:
      - cds-network
    ports:
      - "50051:50051"
      - "8005:8005"
    restart: always
    volumes:
      - target: /opt/app/onap/blueprints/deploy
        type: volume
        source: blueprints-deploy
  py-executor-default:
    depends_on:
      - db
      - nats
    image: onap/ccsdk-py-executor
    container_name: py-executor-default
    hostname: py-executor-default
    networks:
      - cds-network
    ports:
      - "50052:50052"
    restart: always
    volumes:
      - target: /opt/app/onap/blueprints/deploy
        type: volume
        source: blueprints-deploy
    environment:
      APP_NAME: py-executor
      BUNDLEVERSION: 1.0.0
      APP_CONFIG_HOME: /opt/app/onap/config
      STICKYSELECTORKEY:
      ENVCONTEXT: dev
      APP_PORT: 50052
      AUTH_TYPE: tls-auth
      LOG_FILE: /opt/app/onap/logs/application.log

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/mysql/data
      o: bind
  nats-store:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/nats/store
      o: bind
  blueprints-deploy:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/blueprints/deploy
      o: bind
  controller-config:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/cds/cds-controller/config
      o: bind

networks:
  cds-network:
    driver: bridge
